# Generated by Django 4.1.7 on 2023-03-10 18:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartproduct",
            name="cart",
        ),
        migrations.RemoveField(
            model_name="cartproduct",
            name="product",
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="CartProduct",
        ),
    ]
