# Generated by Django 4.1.7 on 2023-03-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image_url",
            field=models.CharField(blank=True, max_length=2083),
        ),
    ]
